extends:
    - vue
    - eslint:recommended
    - google
plugins:
    - vue
env:
    browser: true
rules:
    semi: ["error", "always"]
    no-console: ["error", { "allow": ["warn", "error"] }]
globals:
    WEBPACK_APP_VERSION: true
    WEBPACK_TIMESTAMP: true
